### ISSUE TITLE
Ufuoma -- Dashboard query

### ISSUE THREAD

**Issue by Ria-Kay** [ucmt10/CI536#1]
(21/03/2023) 
Following on from this, can we add a dashboard page once having logged in, which displays again the option to sell, to buy, messages etc...?

**Comment by Ria-Kay** [comment]
added in a basic log in area when the log in button is pressed

**Comment by Ria-Kay** [comment]
could combine this with the log in by making a log in screen before access to main index page, and then users can easily access all other private data. itll prolly work better with the php anyway ill add my tests for this as a branch before committing it to main if it works

**Comment by ucmt10** [comment]
if there is a login page before the main index page then that will prohibit people from browsing? Do we want people to have to login before gaining entry to the sight? Does this mean that we will only be allowing students with an '@brighton' or '@sussex' account to use the sight for example?

**Comment by Ria-Kay** [comment]
yh the main problem i keep having is finding away to keep it browsable finding a way to differentiate between user logged in and not logged in isnt really working for me, have u got anyway working on ur end?

**Comment by ucmt10** [comment]
I'm trying to keep it as:
 allowing the user to keep the browsing option open but the option to buy an item prompts you to log in before continuing to make the purchase

**Comment by Ria-Kay** [comment]
so far ive got the php index working to the point where itll take user info and store it in a database on brighton domains, ik it has phone in there ignore that part lol
Heres a link to it could u try and add in some dummy info so i can see if other users info is correctly added to the database?
https://rk506.brighton.domains/intgroup/login.php
if u can get the part that prompts a log in done ive already mostly got the sign up done ig i can make it as for the proper info and everything, then i think we should be good

**Comment by ucmt10** [comment]
I just used the login function and: 

img width="1188" alt="Screenshot 2023-04-04 at 11 45 20" src="https://user-images.githubusercontent.com/99745782/229768725-e7b96324-6891-4821-a584-422835d2370f.png">

**Comment by Ria-Kay** [comment]
okay so im p sure its fixed?
https://rk506.brighton.domains/intgroup/login.php
i ended up having the same error after trying to change some stuff on server side but i think its back up now, we should be able to use a similar system to store user input on for info about the things theyre selling.
Ik we havent much talked about the actual buisness model but i was workshopping a sort of book marketplace thingy? obvs can be anything but thats one idea.

**Comment by Ria-Kay** [comment]
solved!
